spring:
  application:
    name: onemoment
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  #DataBase
  datasource:
    url: jdbc:mysql://onemoment-db.cda4coea44n3.ap-northeast-2.rds.amazonaws.com:3306/onemoment
    username: ${DB_USERNAME} #[DB_USERNAME]
    password: ${DB_PASSWORD} #[DB_PASSWORD]
    driver-class-name: com.mysql.cj.jdbc.Driver #[JDBC DRIVER]

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#Swagger
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true # 예쁘게
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /swagger # 접속경로
    groups-order: DESC # 내림차순
    tags-sorter: alpha
    operations-sorter: method
    #alpha(알파벳 순 정렬), method(HTTP메소드 순)
    disable-swagger-default-url: true
    display-request-duration: true
  paths-to-match:
    - /**

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKETNAME}